name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Package to IPA for Sideloading
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -qq -r kicapps.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: kicapps-ios-app
          path: kicapps.ipa
